---
version: '3'
tasks:
  init:
    desc: Terraform init
    summary: Terraform init
    aliases: [tfi, tf-init, tfinit]
    cmds:
      - cmd: terraform -chdir=$WORKING_DIR init
    preconditions:
      - sh: terraform --version
        msg: '`terraform` binary was not found in PATH'
  # ──────────────────────────────────────────────────────────────────────────────
  validate:
    desc: Terraform validate
    summary: Terraform validate
    aliases: [tfv, tf-validate, tfvalidate, validate-terraform]
    deps: [init]
    cmds:
      - cmd: terraform validate
    status:
      - '[ -d "{{.ROOT_DIR}}/.terraform" ] && exit 0 || exit 1'
    preconditions:
      - sh: terraform --version
        msg: '`terraform` binary was not found in PATH'
  # ──────────────────────────────────────────────────────────────────────────────
  plan:
    desc: Terraform plan
    summary: Terraform plan
    aliases: [tfp, tf-plan, tfplan]
    deps: [init]
    cmds:
      - cmd: terraform -chdir=$WORKING_DIR plan"
    preconditions:
      - sh: terraform --version
        msg: '`terraform` binary was not found in PATH'
