---
image:
  file: .gp/Dockerfile
  context: .
tasks:
  - name: update packages
    openMode: tab-before
    command: |
      if paru --version > /dev/null 2>&1 ; then
        paru -Syyu --noconfirm ;
        exit 0 ;
      fi
      sudo pacman -Syyu --noconfirm ;
      if aura --version > /dev/null 2>&1 ; then
        sudo aura -Ayyuxac --noconfirm --skipinteg --skippgpcheck ;
      fi
      exit 0 ;
  - name: ensure just is installed
    openMode: tab-before
    command: |
      if ! just --version > /dev/null 2>&1 ; then
        curl \
        --proto '=https' \
        --tlsv1.2 -sSf "https://just.systems/install.sh" \
        | sudo bash -s -- --to /usr/local/bin
      fi
      exit 0 ;
  - name: ensure 'Task' is installed
    openMode: tab-before
    before: |
      if ! task --version > /dev/null 2>&1 ; then
        if [ "$(which "go-task" 2>/dev/null)" != "" ]; then
          sudo ln -sf "$(which "go-task" 2>/dev/null)" "/usr/local/bin/task"
        fi
      fi
      exit 0 ;
    command: |
      if ! task --version > /dev/null 2>&1 ; then
        dir="$(mktemp -d)" \
        && pushd "$dir" > /dev/null 2>&1 \
        && git clone --bare "https://aur.archlinux.org/go-task-bin.git" .git \
        && git fetch --all \
        && git config --local --bool core.bare false \
        && git reset --hard \
        && makepkg -sicr --noconfirm --needed \
        && popd > /dev/null 2>&1 \
        && rm -rf "$dir"
      fi
      if [ "$(which "go-task" 2>/dev/null)" != "" ]; then
        sudo ln -sf "$(which "go-task" 2>/dev/null)" "/usr/local/bin/task"
      fi
      exit 0 ;
  - name: Setup pre-commit
    before: |
      pre-commit install ;
      pre-commit install --install-hooks ;
      pre-commit install --hook-type commit-msg ;
      pre-commit install-hooks ;
      exit 0 ;
    command: |
      pre-commit autoupdate ;
      git add .pre-commit-config.yaml ;
      exit 0 ;
  - name: Setup buildx
    openMode: tab-before
    before: |
      echo "${DOCKER_PASSWORD}" \
      | docker login --username "${DOCKER_USERNAME}" --password-stdin
      exit 0 ;
    command: |
      docker buildx create \
        --use \
        --name "$(basename -s ".git" "$(git remote get-url origin)")" \
        --driver docker-container ;
      exit 0 ;
ports:
  - name: syncthing
    port: 8384
    description: syncthing UI
    onOpen: ignore
    visibility: private
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
vscode:
  extensions:
    - https://github.com/pouyakary/comment/releases/download/v11.2.0/comment-v-11.0.2.vsix
