---
image:
  file: .gp/Dockerfile
  context: .
tasks:
  - name: update packages
    openMode: tab-before
    before: |
      sudo pacman -Syyu --noconfirm ;
      sudo aura -Ayyuxac --noconfirm --skipinteg --skippgpcheck ;
  - name: ensure just is installed
    openMode: tab-before
    before: |
      if ! just --version > /dev/null 2>&1 ; then
        curl \
        --proto '=https' \
        --tlsv1.2 -sSf "https://just.systems/install.sh" \
        | sudo bash -s -- --to /usr/local/bin
      fi
  - name: Setup pre-commit
    before: |
      pre-commit install ;
      pre-commit install --install-hooks ;
      pre-commit install --hook-type commit-msg ;
    command: |
      pre-commit autoupdate ;
      git add .pre-commit-config.yaml ;
  - name: Setup buildx
    openMode: tab-before
    before: |
      echo "${DOCKER_PASSWORD}" \
      | docker login --username "${DOCKER_USERNAME}" --password-stdin
    command: |
      docker buildx create \
        --use \
        --name "$(basename -s ".git" "$(git remote get-url origin)")" \
        --driver docker-container
ports:
  - name: syncthing
    port: 8384
    description: syncthing UI
    onOpen: ignore
    visibility: private
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
vscode:
  extensions:
    - https://github.com/pouyakary/comment/releases/download/v11.2.0/comment-v-11.0.2.vsix
