---
name: "docker"
on:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"
  push:
    branches: [master]
    paths:
      - ".gp/Dockerfile"
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build-and-push:
    name: "build and push docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: "Check Docker Credentials"
        shell: bash
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          set -ex ;
          if [ -z "${DOCKER_USERNAME+x}" ] || [ -z "${DOCKER_USERNAME}" ]; then
            echo "DOCKER_USERNAME is not set" ;
            exit 1 ;
          fi
          if [ -z "${DOCKER_PASSWORD+x}" ] || [ -z "${DOCKER_PASSWORD}" ]; then
            echo "DOCKER_USERNAME is not set" ;
            exit 1 ;
          fi
      - name: "Login to Docker Container Repository"
        run: >
          echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME}
          --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: "build and push docker image"
        shell: bash
        env:
          LOCAL: false
          BUILDKIT_PROGRESS: plain
        run: |
          set -ex ;
          if [ -n "${GITHUB_REF_TYPE+x}" ] && [ -n "${GITHUB_REF_TYPE}" ]; then
            if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
              if [ -n "${GITHUB_REF_NAME+x}" ] && [ -n "${GITHUB_REF_NAME}" ]; then
                export TAG="${GITHUB_REF_NAME#"v"}"
              fi
            fi
          fi
          bash build.sh
