---
name: "docker-buildx"
on:
  workflow_dispatch:
jobs:
  # act --secret GITHUB_TOKEN="$(gh auth token)" --secret DOCKER_USERNAME="fjolsvin" --secret DOCKER_PASSWORD="$(pass 'docker/password')" --env-file "" --job "build-and-push"
  build-and-push:
    name: "build and push docker image"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        id: "check-out-the-repo"
        uses: "actions/checkout@v3"
      - name: "Check Docker Credentials"
        id: "check-docker-credentials"
        shell: bash
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          set -ex ;
          if [ -z "${DOCKER_USERNAME+x}" ] || [ -z "${DOCKER_USERNAME}" ]; then
            echo "DOCKER_USERNAME is not set" ;
            exit 1 ;
          fi
          if [ -z "${DOCKER_PASSWORD+x}" ] || [ -z "${DOCKER_PASSWORD}" ]; then
            echo "DOCKER_PASSWORD is not set" ;
            exit 1 ;
          fi
      - name: "Log in to Docker Hub"
        id: "log-in-to-docker-hub"
        uses: "docker/login-action@v3"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "Set up Docker Buildx"
        id: "set-up-docker-buildx"
        uses: "docker/setup-buildx-action@v3"
        with:
          version: "lab:latest"
          driver: "cloud"
          endpoint: "fjolsvin/dockerized-workspace"
          use: true
      - name: "build and push docker image"
        id: "build-and-push-docker-image"
        shell: bash
        env:
          LOCAL: false
          BUILDKIT_PROGRESS: plain
        run: |
          set -ex ;
          if [ -n "${GITHUB_REF_TYPE+x}" ] && [ -n "${GITHUB_REF_TYPE}" ]; then
            if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
              if [ -n "${GITHUB_REF_NAME+x}" ] && [ -n "${GITHUB_REF_NAME}" ]; then
                export TAG="${GITHUB_REF_NAME#"v"}"
              fi
            fi
          fi
          docker buildx use --global "${{steps.set-up-docker-buildx.outputs.name}}"
          docker buildx bake \
            --set "default.args.CHAOTIC_AUR_KEY=${CHAOTIC_AUR_KEY}"
